"""create tables

Revision ID: c6e0ef9e473b
Revises: 
Create Date: 2026-09-30 16:14:04.894751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e0ef9e473b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), server_default='Untitled session', nullable=False),
    sa.Column('language', sa.Text(), server_default='javascript', nullable=False),
    sa.Column('guests_can_edit', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_persistent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('owner_token_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(slug) between 6 and 32', name=op.f('ck_sessions_slug_length')),
    sa.CheckConstraint('not (is_persistent and expires_at is not null)', name=op.f('ck_sessions_persistent_no_expiry')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_sessions_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('slug', name=op.f('uq_sessions_slug'))
    )
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant')", name=op.f('ck_ai_messages_role_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_ai_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    op.create_index('ix_ai_session_created', 'ai_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(content) <= 1000', name=op.f('ck_chat_messages_content_length')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_chat_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_number > 0', name=op.f('ck_comments_line_positive')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_comments_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_session_id'), 'comments', ['session_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('guest_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='editor', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('owner', 'editor', 'viewer')", name=op.f('ck_participants_role_valid')),
    sa.CheckConstraint('user_id is not null or guest_name is not null', name=op.f('ck_participants_has_identity')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_participants_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    op.create_index('uq_participants_session_user', 'participants', ['session_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id is not null'))
    op.create_table('session_documents',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_documents_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_session_documents'))
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('doc_state', sa.LargeBinary(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('is_manual', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_snapshots_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_snapshots_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots'))
    )
    op.create_index('ix_snapshots_session_created', 'snapshots', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_session_created', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('session_documents')
    op.drop_index('uq_participants_session_user', table_name='participants', postgresql_where=sa.text('user_id is not null'))
    op.drop_table('participants')
    op.drop_index(op.f('ix_comments_session_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_chat_session_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_ai_session_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
